import 'package:flutter/material.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Ludo"),
        ),
        body: SingleChildScrollView(
          child: Row(
            children: [
              box(1, [
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
              ]),
              box(2, [
                Colors.green,
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Colors.green,
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.red,
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Colors.red,
              ]),
              box(3, [
                Colors.green,
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.green,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.black,
                Colors.red,
                Color.fromARGB(255, 70, 6, 1),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 70, 6, 1),
                Colors.red,
              ]),
              box(4, [
                Colors.green,
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.green,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.red,
                Color.fromARGB(255, 70, 6, 1),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 70, 6, 1),
                Colors.red,
              ]),
              box(5, [
                Colors.green,
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Color.fromARGB(255, 1, 43, 3),
                Colors.green,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.red,
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Color.fromARGB(255, 70, 6, 1),
                Colors.red,
              ]),
              box(6, [
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.green,
                Colors.white,
                Color.fromARGB(255, 1, 43, 3),
                Colors.white,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
                Colors.red,
              ]),
              box(7, [
                Colors.white,
                Colors.white,
                Colors.black,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.grey,
                Colors.grey,
                Colors.grey,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 70, 6, 1),
                Colors.white,
              ]),
              box(8, [
                Colors.white,
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Colors.grey,
                Colors.grey,
                Colors.grey,
                const Color.fromARGB(255, 70, 6, 1),
                const Color.fromARGB(255, 70, 6, 1),
                const Color.fromARGB(255, 70, 6, 1),
                const Color.fromARGB(255, 70, 6, 1),
                const Color.fromARGB(255, 70, 6, 1),
                Colors.white,
              ]),
              box(9, [
                Colors.white,
                Color.fromARGB(255, 205, 159, 8),
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.grey,
                Colors.grey,
                Colors.grey,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.black,
                Colors.white,
                Colors.white,
              ]),
              box(10, [
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
              box(11, [
                Colors.yellow,
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Colors.yellow,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.blue,
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                Colors.blue,
              ]),
              box(12, [
                Colors.yellow,
                Color.fromARGB(255, 205, 159, 8),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 205, 159, 8),
                Colors.yellow,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.blue,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.blue,
              ]),
              box(13, [
                Colors.yellow,
                Color.fromARGB(255, 205, 159, 8),
                Colors.white,
                Colors.white,
                Color.fromARGB(255, 205, 159, 8),
                Colors.yellow,
                Colors.black,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.blue,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.white,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                Colors.blue,
              ]),
              box(14, [
                Colors.yellow,
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Color.fromARGB(255, 205, 159, 8),
                Colors.yellow,
                Colors.white,
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                Colors.blue,
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                const Color.fromARGB(255, 3, 56, 99),
                Colors.blue,
              ]),
              box(15, [
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.yellow,
                Colors.white,
                Colors.white,
                Colors.white,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
                Colors.blue,
              ]),
            ],
          ),
        ),
      ),
    );
  }
}

Widget box(int columnNumber, List<Color> colors) {
  return SingleChildScrollView(
    scrollDirection: Axis.horizontal,
    child: Column(
      children: [
        for (var color in colors) borders(color),
      ],
    ),
  );
}

Widget borders(Color color) {
  return Container(
    height: 40,
    width: 40,
    decoration: BoxDecoration(
      color: color,
      border: Border.all(
        color: Colors.grey,
        width: 1.0,
      ),
    ),
  );
}